name: Automated Testing Workflow

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Test with 10 numbers
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_output1.txt
          diff test_output1.txt test_data/test1_expected.txt

      - name: Test with 1 number
        run: |
          python find_lowest_number.py test_data/test2_input.txt test_output2.txt
          diff test_output2.txt test_data/test2_expected.txt

      - name: Test with a blank file
        run: |
          python find_lowest_number.py test_data/test3_input.txt test_output3.txt
          diff test_output3.txt test_data/test3_expected.txt

      - name: Upload test output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-outputs
          path: |
            test_output1.txt
            test_output2.txt
            test_output3.txt
